# Timing mean reversion using IV

https://www.crackingmarkets.com/iv-mean-reversion/

- Simplified idea to use ATM IV from IBKR directly to time price reversal (mean-reversion)

In [ ]:
import pandas as pd
from utils import *

In [16]:
sym = "xli"
stock = pd.read_parquet(f"../../daily_data/{sym}_daily.parquet")
iv = pd.read_parquet(f"../../daily_data/{sym}_iv_daily.parquet")

In [17]:
df = combine_close_prices(stock, iv)
df.head()

                           close  iv_close  next_open
2006-01-06 00:00:00-05:00  31.79  0.158745      31.65
2006-01-09 00:00:00-05:00  32.05  0.104454      31.80
2006-01-10 00:00:00-05:00  31.95  0.101946      31.91
2006-01-11 00:00:00-05:00  31.97  0.104724      31.99
2006-01-12 00:00:00-05:00  31.75  0.109248      31.41

In [18]:
df = calculate_sma_bands(df, base_column="sma20", k=2.0)
df.head()

,close,iv_close,next_open,sma200,sma20,iv_daily_close,upper_band,lower_band
2006-01-06 00:00:00-05:00,31.79,0.158745,31.65,NaN,NaN,0.010000,NaN,NaN
2006-01-09 00:00:00-05:00,32.05,0.104454,31.80,NaN,NaN,0.006580,NaN,NaN
2006-01-10 00:00:00-05:00,31.95,0.101946,31.91,NaN,NaN,0.006422,NaN,NaN
2006-01-11 00:00:00-05:00,31.97,0.104724,31.99,NaN,NaN,0.006597,NaN,NaN
2006-01-12 00:00:00-05:00,31.75,0.109248,31.41,NaN,NaN,0.006882,NaN,NaN

In [19]:
plot_sma_bands_interactive(df)

In [20]:
df = calculate_entry_signals(df, iv_daily_close_threshold=0.01)
df = load_positions(df)

In [21]:
plot_strategy_interactive(df)

In [22]:
trades,fig= strategy_return_distribution(df, position_scaling=True)
fig.show()